version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - neo4j
  neo4j:
    container_name: neo4j4app
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/123456
    volumes:
      - ../dbdata:/data
    # ports:
    #   - "7687:7687"
    #   - "7474:7474"
